---
title: "Senior Research Project"
---

## Overview

For my senior research project, I examined whether early European carbon taxes reduced national CO₂ emissions per capita in the 5 years following their implementation. This project combined applied econometrics, environmental policy analysis, and data visualization to study how carbon tax adoption affected emissions across European countries before the introduction of the European Union Emissions Trading System.

## Research Question

Did early European carbon taxes reduce national CO₂ emissions per capita in the short run?

## Data

I used country-level panel data for European countries from 1985 to 2004, with a final dataset containing 1,160 observations in 27 variables, across 29 countries. The dataset included emissions data, carbon tax adoption timing, and economic and environmental controls such as GDP per capita and average annual temperature.

## Methods

To estimate the effects of carbon tax adoption, I used an Sun & Abraham event study framework with country and year fixed effects. This approach allowed me to compare emissions trends before and after carbon tax adoption while accounting for differences in adoption time, inherent country differences, and shocks across time.

## Key Findings

The results suggested that early European carbon taxes did not lead to large or statistically significant short-run reductions in national CO₂ emissions per capita. This may be because the first taxes were much less intense than carbon taxes today. However, additional analysis suggested some evidence of modest shifts in fossil fuel energy use following adoption.


## Project Materials

- [View GitHub Repository](https://github.com/evantoth1/SeniorExperience)
- [View Final Paper](files/EvanTothFinalDraft.pdf)